// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_passwords, is_chirpy_red)
VALUES (gen_random_uuid(), NOW(), NOW(), $1, $2, false) RETURNING id, created_at, updated_at, email, is_chirpy_red
`

type CreateUserParams struct {
	Email           string
	HashedPasswords string
}

type CreateUserRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Email       string
	IsChirpyRed bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPasswords)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.IsChirpyRed,
	)
	return i, err
}

const deleteAllUser = `-- name: DeleteAllUser :exec
DELETE FROM users
`

func (q *Queries) DeleteAllUser(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUser)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, email, hashed_passwords, is_chirpy_red FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPasswords,
		&i.IsChirpyRed,
	)
	return i, err
}

const updateEmailPassword = `-- name: UpdateEmailPassword :one
UPDATE users
SET email = $2, hashed_passwords = $3, updated_at = NOW()
WHERE id = $1 RETURNING id, created_at, updated_at, email, hashed_passwords, is_chirpy_red
`

type UpdateEmailPasswordParams struct {
	ID              uuid.UUID
	Email           string
	HashedPasswords string
}

func (q *Queries) UpdateEmailPassword(ctx context.Context, arg UpdateEmailPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateEmailPassword, arg.ID, arg.Email, arg.HashedPasswords)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPasswords,
		&i.IsChirpyRed,
	)
	return i, err
}

const upgradeUserByID = `-- name: UpgradeUserByID :one
UPDATE users
SET is_chirpy_red = true
WHERE id = $1 RETURNING id, created_at, updated_at, email, hashed_passwords, is_chirpy_red
`

func (q *Queries) UpgradeUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, upgradeUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPasswords,
		&i.IsChirpyRed,
	)
	return i, err
}
